### PR TITLE
fix: prevent home shell session crash

### LINKED ISSUE #182: [Bug] Shell-mode any command triggers renderer Switch crash (beyond #174)
## Summary

In composer shell mode (`mod+shift+x`), sending any command — including successful ones like `gh --help` and nonexistent ones like `absolutelyfake` — triggers a renderer crash:

```
TypeError: switchFunc(...) is not a function
    at Switch.createMemo.name [as fn]
    at runComputation
    at updateComputation
    ...
```

Full stack from the session:

```
TypeError: switchFunc(...) is not a function
    at Switch.createMemo.name [as fn] (http://localhost:5173/@fs/.../node_modules/.vite/deps/chunk-VL2SL2GY.js?v=db12a2de:1549:29)
    at runComputation (.../chunk-VL2SL2GY.js:734:22)
    at updateComputation (.../chunk-VL2SL2GY.js:717:3)
    at runTop (.../chunk-VL2SL2GY.js:827:7)
    at lookUpstream (.../chunk-VL2SL2GY.js:951:87)
    at runTop (.../chunk-VL2SL2GY.js:811:74)
    at runUserEffects (.../chunk-VL2SL2GY.js:924:18)
    at runUpdates (.../chunk-VL2SL2GY.js:844:17)
    at completeUpdates (.../chunk-VL2SL2GY.js:896:17)
```

## Repro

1. `bun run dev:desktop` on `origin/dev` (or any branch derived from post-#174 dev)
2. Open a session (or new session)
3. Press `mod+shift+x` to enter shell mode
4. Type `gh --help` (or any command, succeeding or failing)
5. Press Enter / Send
6. Renderer crashes with the Switch error above

## Relation to #171 / #174

#174 addressed renderer crashes on **failed** shell commands by replacing Switch with Show inside `packages/ui/src/components/basic-tool.tsx`. Manual reverification shows that (a) the crash now also fires on **successful** commands and (b) it originates from a different `<Switch>` than the one #174 patched — `basic-tool.tsx` no longer contains `<Switch>` in the current tree, so the `switchFunc(...) is not a function` stack must be from another message-part or tool render path.

## Verified

- Reproducible on a clean `origin/dev` worktree (checked at `4274751ab9`, HEAD at issue filing). Not introduced by #180; `#180` does not modify `packages/ui` or any `<Switch>` rendering code.

## Next steps

1. Identify the specific `<Switch>` whose `<Match when={...}>` predicate collapses to undefined when a shell-tool part finishes. Candidate sites: `packages/ui/src/components/message-part.tsx` (multiple Switch blocks at L647, L861, L1348, L2110, L2185).
2. Decide whether to migrate it to Show/conditional render (same pattern as #174) or narrow the Match predicate to never return undefined.
3. Add an e2e regression (extending `packages/app/e2e/prompt/prompt-shell.spec.ts`) covering both success and failure shell output render.

## Refs

- #171 (original shell failure crash issue; closed)
- #174 (first fix; targeted failure path only)

### PR DESCRIPTION
**Pull request by Astro-Han**
## Summary

Fix the renderer crash when shell mode starts from the new session home. The sidebar session row now renders its status indicator with a plain conditional helper instead of a Solid Switch that can evaluate with no matching branch during the new-session store flush. Added e2e coverage for the home shell path.

## Why

PR #174 covered shell rendering inside an existing session, but the home path still crashed after typing `!` and submitting a command because creating the session also inserts a sidebar row with a transient empty indicator state. This PR fixes that remaining path.

## Related Issue

Fixes #182. Follow-up to PR #174.

## How To Verify

```bash
bun --cwd packages/app test:e2e e2e/prompt/prompt-shell.spec.ts --project=chromium --grep "new session home"
bun --cwd packages/app test:e2e e2e/prompt/prompt-shell.spec.ts --project=chromium
bun --cwd packages/app typecheck
git diff --check
```

## Screenshots or Recordings

Not applicable. This fixes a crash path without changing visible UI.

## Checklist

- [x] I linked the related issue, or stated why there is no issue
- [x] This PR has type, scope, and priority labels, or I requested maintainer labeling
- [x] I listed the relevant verification steps, including tests when behavior changed
- [x] I manually checked visible UI or copy changes when needed, with screenshots or recordings
- [x] I considered macOS and Windows impact for desktop, packaging, updater, signing, paths, shell, or permissions changes
- [x] I called out docs, release notes, dependencies, permissions, credentials, deletion behavior, or generated/local file changes when relevant
- [x] I am targeting `dev`, and my PR title and commit messages use Conventional Commits in English

## Summary by CodeRabbit

* **Tests**
  * Added new end-to-end test coverage for shell mode, validating shell command execution and output verification in session workflows.

* **Refactor**
  * Simplified session status indicator logic for improved code maintainability.

### CODE REVIEW

File: packages/app/src/pages/layout/sidebar-items.tsx [hunk 1]
```diff
@@ -101,6 +101,13 @@ const SessionRow = (props: {
   const language = useLanguage()
   const title = () => sessionTitle(props.session.title)
   const skill = createMemo(() => getPawworkSkillMeta(props.session.skill))
+  const indicator = () => {
+    if (props.isWorking()) return <Spinner class="size-[15px]" />
+    if (props.hasPermissions()) return <div class="size-1.5 rounded-full bg-surface-warning-strong" />
+    if (props.hasError()) return <div class="size-1.5 rounded-full bg-text-diff-delete-base" />
+    if (props.unseenCount() > 0) return <div class="size-1.5 rounded-full bg-text-interactive-base" />
+    return null
+  }
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/app/src/pages/layout/sidebar-items.tsx:110]: Not changing this one. The helper is intentionally a small plain conditional to avoid the Solid Switch empty-branch crash. Solid tracks dependencies dynamically inside the JSX computation, so when `isWorking()` is true this expression only subscribes to that accessor and does not re-run because `unseenCount()` changes. The only time it recreates the element is when the active indicator state changes, which is the desired UI update. Adding two memos here would add more state for a hypothetical flicker risk without fixing a demonstrated bug.

File: packages/app/e2e/prompt/prompt-shell.spec.ts [hunk 2]
```diff
@@ -124,6 +124,48 @@ test("shell mode renders command failures without crashing the renderer", async
...
+test("shell mode can start from the new session home", async ({ page, project }) => {
+  test.setTimeout(120_000)
+
+  const errors = capturePageErrors(page)
+  const cmd = process.platform === "win32" ? "dir" : "command ls"
+
+  try {
+    await project.open()
+    const sessionID = await project.shell(cmd)
+
```
[the remark this answers is not in the document]
Comment (Astro-Han) [reply packages/app/e2e/prompt/prompt-shell.spec.ts:136]: Verified against the fixture. `project.shell()` delegates to `send()`, and `send()` already calls `trackSession(next.sessionID, active.directory)` before returning the session id. Adding another `project.trackSession(sessionID)` in this test would be redundant and would not change teardown behavior.
