### ISSUE TITLE
Flaky unit-app: mock.module leakage across test files causes order-dependent failures

### ISSUE THREAD

**Issue by Astro-Han** [Astro-Han/pawwork#957]
Sourced from CI investigation on #951.

## Symptom

`unit-app` intermittently fails in CI while passing locally and on re-run (no code change). Two error signatures, both at module-load/first-use time:

- `TypeError: Persist.workspace is not a function`
- `SyntaxError: Export named 'useNavigate' not found in module '@solidjs/router'`

Tests hit: `createChildStoreManager` (`src/context/global-sync/child-store.test.ts`), `session action readiness` (`src/pages/session/session-action-readiness.test.ts`), `directory-scoped prompt history targets`. Each of these passes in isolation.

Example failing run: https://github.com/Astro-Han/pawwork/actions/runs/26518663246 (re-run of the same commit went green).

## Root cause

`bun test` runs all files in one process, and `mock.module(...)` is **process-global and not auto-restored between files**. A test that replaces `@/utils/persist` or `@solidjs/router` with a partial mock and never restores it leaks that mock into every file that runs afterward. When a leaking file is scheduled before tests that use the real module, those tests see the partial mock (missing `Persist.workspace` / `useNavigate`) and fail.

File execution order differs between local (macOS/APFS) and CI (Linux/ext4), and shifts whenever the test file set changes (e.g. merging new files), so the failure is **order-dependent and intermittent** rather than deterministic.

## Suspected leak sources

Files that `mock.module` persist/router; most have no `mock.restore()` / `afterEach` cleanup:

- src/context/{local,terminal,comments,prompt,models}.test.ts
- src/components/file-tree.test.ts
- src/components/prompt-input/{draft-isolation.integration,submit,submit-ownership}.test.ts
- src/hooks/use-providers.test.ts
- src/pages/session/{session-action-readiness,session-layout,use-session-followups}.test.ts

## Possible fixes

- Restore module mocks after each suite (`mock.restore()` in `afterEach`/`afterAll`), or
- Enforce isolation so module mocks cannot leak across files, or
- Audit the list above and add missing restores.

## Impact / priority

Not a product bug and not a hard blocker (re-run clears it), but it wastes time and erodes trust in the suite ("red? just re-run") which risks masking real regressions. Low-priority but worth fixing as the test count grows.

**Comment by Astro-Han** [comment]
Correction to the "re-run clears it" guidance, from #951 CI:

Re-running the **same** workflow run does **not** clear it. CI builds on the branch+base merge commit, so a re-run reuses the identical test-file set and execution order — the leaking file stays scheduled ahead of the victims and the failure reproduces deterministically. On #951 unit-app failed, then failed again on a same-commit re-run with the identical 33s signature.

What actually clears it is a **new commit**: that produces a fresh merge commit, which can shift file discovery order so the leaking file no longer precedes the victims. On #951 the very next pushed commit made unit-app pass first try (no test change touched those files).

So the practical workaround is "push a new commit / rebase", not "re-run the job" — but the real fix remains adding mock cleanup / isolation so order stops mattering.

**Comment by Astro-Han** [comment]
Closing as resolved. The order-dependent CI failures this issue tracked have been fixed:

- PR #1079 scoped the leaking `showToast` mock.module stub (submit.test.ts / attachments.test.ts) so it no longer poisons later suites.
- PR #1096 extracted pure prompt-equality helpers so prompt-input tests no longer load @solidjs/router out of order.

Both merged 2026-06-03 (after this issue was filed 2026-05-27). The actively-breaking signatures are gone.

The remaining latent, non-breaking `mock.module` stubs in 9 other app test files are tracked as preventive hardening in #1084, which carries the full scoped-spyOn migration.
